### ISSUE TITLE
Can't find the script file

### ISSUE THREAD

**Issue by Wangqkoe** [TheJeran/Blender-Colormaps#1]
This project has no script file but a README.md. 

Is this a missing issue or is the script not ready yet?

The effects posted in the README look pretty cool, I'm very looking forward to try it.

**Comment by TheJeran** [comment]
How are you trying to install it? 

Go here https://github.com/TheJeran/Blender-Colormaps/releases/tag/release and download the blender_colormaps zip

Make sure you've installed the colormaps into your blender native python as described in the readme

**Comment by Wangqkoe** [comment]
Perfect! 

I downloaded the ZIP file on the code page instead of the release page.
