### ISSUE TITLE
Pastel colors instead of true colors

### ISSUE THREAD

**Issue by kmarchais** [TheJeran/Blender-Colormaps#3]
Hello, 

Thank you for this helpful project.
For at least some of the colormaps, the colormap obtained results in kind of pastel colors instead of true colors.
For example with the viridis colormap, here is the true colormap : 
![viridis](https://github.com/TheJeran/Blender-Colormaps/assets/22714778/bbb61eed-7f92-4a7d-9b00-7b587b16620f)

However, when generated with this addon, it gives the left color ramp on the following image. The color ramp of the right is with the true colours picked on the true colormap.
![2023-06-28 17_46_34-Blender](https://github.com/TheJeran/Blender-Colormaps/assets/22714778/379f2f75-758a-4bbf-a710-b9d29ee03cc6)

I understand that the colormaps comes directly from matplotlib but it appears that the colors are not really the one expected. Do you know what is the issue ?

Thank you

**Comment by TheJeran** [comment]
Thanks for writing.

This was a problem my coworker mentioned and I couldn't find the issue. I admittedly didn't look super hard. But the code is this

```
for e in el:
        pos = e.position
        e.color = cmap(pos)
```

Where _el_ is the elements or "ticks" and _cmap_ is the colormap from matplotlib.  So the position should return the correct color and there shouldn't be this weird issue. 

There is another bug that pops up every now and then (Nothing bad but you may notice an error every now and then if you deselect a node in any node editor) that I want to fix eventually. So I'll give this another look and see if either the position or the color are not what they are supposed to be. 

I'm pretty busy, but I'll give this a look on Tuesday.  If you you know python and can figure it out for me let me know.

**Comment by kmarchais** [comment]
Thanks for your answer, it's been a few days that I'm working on it and can't find the issue neither.

When I print the colors of the colormap, the rgb values are the same as the ones that generate this pastel style. But it works well with matplotlib apparently so I don't understand what's the trick.

**Comment by TheJeran** [comment]
I've been looking into this and I believe it is actually a Blender issue. I've checked and when inputting the RGB values into blender you get the wrong Hex codes. It's simply the wrong colors. I'm reporting the bug now, do you have an account on https://projects.blender.org/blender/blender/ ? I can tag you.

**Comment by kmarchais** [comment]
Oh ok I see, you can find me as @kmarchais there too, thanks!

**Comment by TheJeran** [comment]
Found the solution!

Turns out blender takes Linear RGB values whereas matplotlib gives sRGB values. So it's a quick conversion. 

I'll push this fix along with the other bug next week. But if you have an IDE you can change Lines 152 and 177 in the _init_ file to

`e.color = [i**2.2 for i in cmap(pos)]`

**Comment by kmarchais** [comment]
Oh very nice, I'll check tomorrow, thanks a lot!
