### ISSUE TITLE
colormaps library

### ISSUE THREAD

**Issue by orioltinto** [TheJeran/Blender-Colormaps#7]
Hi, 
I found the add-on after implementing something similar myself, nice job.

Something that might be useful to you is the python package **colormaps** (I'm not the author):
https://github.com/pratiman-91/colormaps/tree/main/colormaps

It integrates colormaps from many other libraries that are easy to access and use. 

A simple example:

```python
import colormaps as cmaps

def create_color_ramp(nodes, colormap_name, location= (0,0), steps=21):
    # Create color ramp
    color_ramp = nodes.new(type="ShaderNodeValToRGB")
    color_ramp.color_ramp.color_mode = 'HSV'

    color_ramp.location = location

    # Change color ramp
    elements = color_ramp.color_ramp.elements
    elements.remove(elements[0])

    elements[0].position = 0

    # Get colormap based on name
    cmap = getattr(cmaps, colormap)
    step_length = 1.0/steps
    for i in range(1, steps+1):
        pos = step_length*i
        color_ramp.color_ramp.elements.new(pos)
    
    # Set color of elements
    for element in elements:
        element.color = cmap(element.position)
    
    return color_ramp
```

**Comment by TheJeran** [comment]
Sorry for never responding to this.

There are two collections in there that I quite like. I'll look into adding those in the not too distant future.

**Comment by TheJeran** [comment]
Implementing these over the weekend
